### ISSUE TITLE
Update for Serilog 2.0

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-nlog#1]
From: https://github.com/serilog/serilog/issues/801

**Comment by HakanL** [comment]
Submitted a PR, but I couldn't get the build.ps1 to run so I wasn't able to test it :(

**Comment by HakanL** [comment]
Tested in my project, works great, thanks for the quick merge!

**Comment by nblumhardt** [comment]
Great, thanks for the feedback.
